### ISSUE TITLE
Changes to colour and name attributes are not triggering a re-render on Firefox or Edge

### ISSUE THREAD

**Issue by svanherk** [BrightspaceUI/profile-image#10] opened 2018-09-04 17:42 UTC
Chrome and IE11 seem to be updating properly.  Did not test Safari.

**Comment by mtjandra** [comment] 2018-09-05 14:11
I propose we close this issue. After testing in Firefox, Edge, and Internet explorer I could not reproduce the issue when using javascript to update the components.
Ex:
```
var initials = document.querySelector('#profile-with-initials');
initials .setAttribute('first-name', 'ER'); // Successfully updates

var image = document.querySelector('#profile-with-image');
image .setAttribute('image-url', './img/picture.png');  // Successfully updates
```

**Comment by svanherk** [comment] 2018-09-05 17:43
Sounds good, I'm surprised by this but I use Chrome as my main development browser, and may have just never noticed this inconsistency across browsers.

**Closed** 2018-09-05 20:38 UTC
